### ISSUE TITLE
Access token error handling

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [vinkla/instagram#113]
Hi,

Is there a way to handle error if access token is invalid ?
Suddenly it threw an error 500 on the whole website. 
I had to regenerate access token to solve it, but I would like to avoid the whole site getting broken if it happens again.

I made some tries, and had a look at instagram.php but can't manage to make it work with an if statement before calling $instagram->media().

Any idea please ?

**Comment by vinkla** [comment]
Currently we rely on the error messages sent by Instagram. You can do an `try/catch` on `InstagramException` to fetch the error message. We wont currently add any new features since Instagram probably will close down this API early next year. Which will probably lead to total rewrite of this package.

**Comment by ShapesGraphicStudio** [comment]
Hi,
OK, I understand.
Thanks for the quick and efficient answer!
