### ISSUE TITLE
does this violate Instagram's TOS?

### ISSUE THREAD

**Issue by FranciscoG** [vinkla/instagram#50]
I see that you're using this URL method to access the feed:  "https://www.instagram.com/%s/media".  I saw this method mentioned in a [stackoverflow response](http://stackoverflow.com/a/37586434/395414) and a comment in that response said that it violated Instagram's Terms of Service

this was the comment:
> While this works, it a) may not always work (as it's not part of the public API) and b) is in violation of the TOS, which states "You must not access Instagram's private API by means other than those permitted by Instagram." help.instagram.com/478745558852511

In their specific API documentation there is one line that looks concerning:
https://www.instagram.com/about/legal/terms/api/

> 16 Don't use the Instagram API to simply display User Content, import or backup content, or manage Instagram relationships, without our prior permission.

All of this is confusing and I wish Instagram would just either explicitly say that this endpoint is allowed and will stay or take it down.

**Comment by vinkla** [comment]
To be honest I've thought about that at all. Not sure what to do. I know this approach is common since they locked all their API endpoints behind the access token bars back in 2016.

> 16. Don't use the Instagram API to simply display User Content, import or backup content, or manage Instagram relationships, without our prior permission.

If they don't want us to use their public API they could lock this endpoint behind OAuth as well. If they don't like how we fetch data and/or ever read this issue they can reach out to me and I will update or remove this package.

> All of this is confusing and I wish Instagram would just either explicitly say that this endpoint is allowed and will stay or take it down.

I agree. In my opinon they should provide easy-to-use endpoints that doesn't require login. That goes for Facebook and Twitter as well.

**Comment by FranciscoG** [comment]
yeah exactly.  I just want to pull my own feed into my own website and they don't have something in their developer API docs for that.  It's all about creating some sort of app to authenticate other users and you have to basically use that to get your own feed.  so annoying.

**Comment by vinkla** [comment]
> Yeah exactly. I just want to pull my own feed into my own website and they don't have something in their developer API docs for that. It's all about creating some sort of app to authenticate other users and you have to basically use that to get your own feed. So annoying.

I agree. They should come up with something better.
